branches:
  only:
    - master
    - "/^v.*$/"

language: python
python:
  - '3.6'

env:
  - DB=sqlite
  - DB=mysql
  - DB=pgsql

addons:
  postgresql: '9.6'

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS pytest_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE pytest_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS pytest_test;'; fi"

install:
  - pip install --upgrade pip
  - pip install -e .[tests]

script: pytest

jobs:
  include:
    - stage: Test PostgresSQL
      env: DB=pgsql TEST_DATABASE_URL=postgresql://postgres@localhost:5432/pytest_test
      addons:
        postgresql: '9.6'

    - stage: Test MySQL
      env: DB=mysql TEST_DATABASE_URL=mysql+mysqldb://root@127.0.0.1/pytest_test
      addons:
        mysql: '5.7'

    - stage: Test SQLite
      env: DB=sqlite TEST_DATABASE_URL=sqlite:///:memory:/pytest_test
      addons:
        sqlite: '9.6'

deploy:
  provider: pypi
  distributions: 'sdist bdist_wheel'
  skip_existing: true
  user: jeancochrane
  password:
    secure: d9H2Arvdy8CSH/TgWepHjhrLEQnD87BQ6BeSh7NRXPWcQb34KqKE4kkgos3r1RdQNurMVFRwEElfaLrQUhHInvSRQxPpjfX8ObjbndSbNWIGEODc0VieE0WQOApKezd38HNj3XrGXtuzUta/IKN+UOIZYka4LouT7uzH9/cz00+HIfRZg6N65ngataWfxJhempfXdh7iqTtUTu7Cn0O/ow4ey/654g9F+ElpvowVaq//2w1f5fLQIeWnsFs5X1cAxQ3XV0M4xU9dDvUEXtFXUSIjQAmzd4ovGS6Ri1/9okONeCb8A2FPjOKin8mvqNRtIKZJxoXSli3HlvrJozyoJjD+mVFUUYae81lXN08RsI005Ngqyc5hm1ibiX80Uiul4lLBqiBWQoRsKpaMBfFqkMzCcLKxaZAWJoUEuqlXcufQbWcOXrlmDbSOFn9gHxLxwISWUwm9M5/9bABjc5B8tPJqy3U4/q7plV6HDgXkBllm2bqYUIl8L+kff+LIV3wY1Txq8Mg4ZtQu1mwoB0ysQyinQBRu8CEvRo2qkepClio5Up3Fim43oSQnBOg6B3GFkNl1ikCM0dYqGW+d7bLqKuCeqWPgko+JYnVOTSbq+RULGp9tAFqIvRMN+Ih2Xlk4zy4bh8eVrESE+V0nv5oYCJW3loDDKlQzd+QTmQlLasM=
  on:
    tags: true
